fixing create mapping and style ref #35
brazil-data-cube/lccs.py pull request #37
Opened 2021-02-12 19:57 UTC by fabianazioti

2021-02-12 20:18 UTC, raphaelrpl approved these changes

2021-02-13 05:42 UTC, M3nin0 requested changes

2021-02-13 05:42 UTC, M3nin0 commented on examples/available_mappings.py
> +service = LCCS("'https://brazildatacube.dpi.inpe.br/lccs/")
You may need to remove the quote

2021-02-13 05:42 UTC, M3nin0 commented on examples/classification_system_metadata.py
> +service = LCCS("http://brazildatacube.dpi.inpe.br/lccs/")
HTTPS ?

2021-02-13 05:42 UTC, M3nin0 commented on examples/classification_systems.py
> +service = LCCS("http://brazildatacube.dpi.inpe.br/lccs/")
HTTPS

2021-02-13 05:42 UTC, M3nin0 commented on examples/ex-01.py
> +service = lccs.LCCS(url)
maybe insert a string with server url text (e. g. "server url")

2021-02-13 05:42 UTC, M3nin0 commented on examples/style.py
>  service = LCCS("http://brazildatacube.dpi.inpe.br/dev/lccs/")
HTTPS

2021-02-18 14:08 UTC, mzaglia requested changes

2021-02-18 14:08 UTC, mzaglia commented on tests/tests_lccs/jsons/class.json
> +      "href": "http://localhost:5000/classification_systems1/classes",
classification_systems/1/classes ?

2021-02-18 14:18 UTC, mzaglia approved these changes

2021-02-19 12:00 UTC, M3nin0 approved these changes

2021-03-12 12:46 UTC, raphaelrpl approved these changes

2021-03-12 12:46 UTC, merged